# Copyright 2017 Istio Authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

##################################################################################################
# identities Adapter PROD - UPDATE BY HAND OR WITH A RELEASE JOB
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: identities
  labels:
    app: identities
spec:
  ports:
  - port: 9090
    name: http
  selector:
    app: identities
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: identities-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: identities
        version: v1
    spec:
      containers:
      - name: identities
        image: dennisseidel/identitiesadapter:0.0.2
        imagePullPolicy: IfNotPresent
        env:
          - name: MODE
            value: prod
          - name: auth0_endpoint
            value: https://d10l.eu.auth0.com
          - name: apigee_management_endpoint
            value: https://api.enterprise.apigee.com/v1/organizations/denseidel-trial
          - name: apigee_auth_endpoint
            value: https://api.enterprise.apigee.com/v1/organizations/denseidel-trial
          - name: MONGODB_URL
            valueFrom:
              secretKeyRef:
                name: identities-secrets
                key: MONGODB_URL
          - name: apigee_client_id
            valueFrom:
              secretKeyRef:
                name: identities-secrets
                key: apigee_client_id
          - name: apigee_client_secret
            valueFrom:
              secretKeyRef:
                name: identities-secrets
                key: apigee_client_secret
          - name: auth_client_id
            valueFrom:
              secretKeyRef:
                name: identities-secrets
                key: auth_client_id
          - name: auth_client_secret
            valueFrom:
              secretKeyRef:
                name: identities-secrets
                key: auth_client_secret
          - name: apigee_client_id
            valueFrom:
              secretKeyRef:
                name: identities-secrets
                key: apigee_client_id
          
        ports:
        - containerPort: 9090
---
##################################################################################################
# identities Adapter Canery
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: identities
  labels:
    app: identities
spec:
  ports:
  - port: 9090
    name: http
  selector:
    app: identities
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: identities-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: identities
        version: canary
    spec:
      containers:
      - name: identities
        image: dennisseidel/identitiesadapter:0.0.18
        imagePullPolicy: IfNotPresent
        env:
          - name: MODE
            value: prod
          - name: auth0_endpoint
            value: https://d10l.eu.auth0.com
          - name: apigee_management_endpoint
            value: https://api.enterprise.apigee.com/v1/organizations/denseidel-trial
          - name: apigee_auth_endpoint
            value: https://api.enterprise.apigee.com/v1/organizations/denseidel-trial
          - name: MONGODB_URL
            valueFrom:
              secretKeyRef:
                name: identities-secrets
                key: MONGODB_URL
          - name: apigee_client_id
            valueFrom:
              secretKeyRef:
                name: identities-secrets
                key: apigee_client_id
          - name: apigee_client_secret
            valueFrom:
              secretKeyRef:
                name: identities-secrets
                key: apigee_client_secret
          - name: auth_client_id
            valueFrom:
              secretKeyRef:
                name: identities-secrets
                key: auth_client_id
          - name: auth_client_secret
            valueFrom:
              secretKeyRef:
                name: identities-secrets
                key: auth_client_secret
          - name: apigee_client_id
            valueFrom:
              secretKeyRef:
                name: identities-secrets
                key: apigee_client_id
        ports:
        - containerPort: 9090
---
##################################################################################################
# RouteRule identities Adapter
##################################################################################################
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: mirror-idetities-traffic-to-canery
spec:
  destination:
    name: identities
  precedence: 11
  route:
  - labels:
      version: v1
    weight: 0
  - labels: 
      version: canary
    weight: 100
---
###########################################################################
# Service Mongodb
###########################################################################
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    name: mongo
  selector:
    app: mongodb
---
###########################################################################
# Deployment Mongodb
###########################################################################
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
        version: v1
    spec:
      containers:
      - name: mongodb 
        image: bitnami/mongodb:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: MONGODB_DATABASE
            value: identities
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: identities-secrets
                key: MONGODB_USERNAME
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: identities-secrets
                key: MONGODB_PASSWORD
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: identities-secrets
                key: MONGODB_ROOT_PASSWORD
        ports:
        - containerPort: 27017
---