---
version: "3"
services:
  swaggereditor:
    image: swaggerapi/swagger-editor
    ports:
      - "80:8080"
  consumer-service:
    image: consumer-service:latest
    build: .
    environment:
      - MODE=prod
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      - .:/code
    ports:
      - "9090:5000"
    command: connexion run swagger/swagger.yaml --mock=all
networks:
  default:
    external:
      name: default-network