---
version: "3"
services:
  swaggereditor:
    image: swaggerapi/swagger-editor
    ports:
      - "80:8080"
  identities-service:
    image: identities-service:latest
    build: .
    environment:
      - MODE=prod
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_URL=$MONGODB_URL
      - auth_client_id=$auth_client_id
      - auth_client_secret=$auth_client_secret
      - apigee_client_id=$apigee_client_id
      - apigee_client_secret=$apigee_client_secret
      - auth0_endpoint=$auth0_endpoint
      - apigee_management_endpoint=$apigee_management_endpoint
      - apigee_auth_endpoint=$apigee_auth_endpoint
    ports:
      - "9090:5000"
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_DATABASE=identities
networks:
  default:
    external:
      name: default-network